### ISSUE TITLE
Login and sign up routing issues

### ISSUE THREAD

**Issue by Debikasarkar713** [Debikasarkar713/Project2-Bookfeed#1]
Hello,

I am having a tough time understanding as to why my login and sign up page are not correctly rendering to the page. My login page is giving a cannot GET and my sign up can't find my sign up directory in views. I have checked over the code a few times and have showed it to others however I can't seem to find whats wrong. This problem has been occurring for a few hours now so I would really like some feedback and get this fixed in order to complete my project.

@gittheking @jasonseminara @trevorpreston @rapala61 @irwin

**Comment by rapala61** [comment]
Hi. Please close this issue.
